apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: counter-api-pipelinerun-
spec:
  pipelineRef:
    name: ci-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
  params:
    - name: git-repo
      value: "https://github.com/{your_github_account}/ci-cd-final-project.git"
  serviceAccountName: pipeline
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
      resources:
        inputs:
          - name: repository
            resourceRef:
              name: git-repo
    - name: lint
      taskRef:
        name: flake8-lint
      resources:
        inputs:
          - name: source
            workspace: shared-workspace
    - name: test
      taskRef:
        name: run-nose-tests
      resources:
        inputs:
          - name: source
            workspace: shared-workspace
    - name: build
      taskRef:
        name: docker-build
      resources:
        inputs:
          - name: source
            workspace: shared-workspace
    - name: deploy
      taskRef:
        name: deploy-to-openshift
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-nose-tests
spec:
  steps:
    - name: run-tests
      image: python:3.9-slim
      script: |
        pip install -r requirements.txt
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
